# Generated by Django 3.1.6 on 2021-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, verbose_name='نام شرکت')),
                ('name', models.CharField(max_length=300, verbose_name='نام نماینده')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='شماره تلفن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='تصویر یا لوگو برند')),
                ('image', models.ImageField(blank=True, null=True, upload_to='agents', verbose_name='تصویر نماینده')),
                ('State', models.CharField(max_length=300, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'نماینده',
                'verbose_name_plural': 'نمایندگان',
            },
        ),
    ]
