# Generated by Django 3.1.6 on 2021-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='Logo',
        ),
        migrations.AddField(
            model_name='agents',
            name='email',
            field=models.EmailField(default='1', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
