# Generated by Django 3.1.6 on 2021-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_auto_20210304_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
