# Generated by Django 3.1.6 on 2021-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_auto_20210304_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='company',
            new_name='company_en',
        ),
        migrations.RenameField(
            model_name='agents',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='agents',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='agents',
            old_name='State',
            new_name='state_en',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='image',
            new_name='image_en',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='agents',
            name='company_fa',
            field=models.CharField(default=1, max_length=300, verbose_name='نام شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='company_tr',
            field=models.CharField(default=1, max_length=300, verbose_name='نام شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='agents',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='agents',
            name='name_fa',
            field=models.CharField(default=1, max_length=300, verbose_name='نام نماینده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='name_tr',
            field=models.CharField(default=1, max_length=300, verbose_name='نام نماینده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='state_fa',
            field=models.CharField(default=1, max_length=300, verbose_name='نام استان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='state_tr',
            field=models.CharField(default=1, max_length=300, verbose_name='نام استان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brands',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='brands',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='brands',
            name='image_fa',
            field=models.ImageField(blank=True, null=True, upload_to='brands', verbose_name='تصویر یا لوگو برند'),
        ),
        migrations.AddField(
            model_name='brands',
            name='image_tr',
            field=models.ImageField(blank=True, null=True, upload_to='brands', verbose_name='تصویر یا لوگو برند'),
        ),
        migrations.AddField(
            model_name='brands',
            name='title_fa',
            field=models.CharField(default=1, max_length=300, verbose_name='نام برند'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brands',
            name='title_tr',
            field=models.CharField(default=1, max_length=300, verbose_name='نام برند'),
            preserve_default=False,
        ),
    ]
