# Generated by Django 3.1.6 on 2021-03-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_auto_20210306_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='image_en',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='image_fa',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='image_tr',
        ),
    ]
