# Generated by Django 3.1.6 on 2021-03-10 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_auto_20210310_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='timeadd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='timeadd'),
            preserve_default=False,
        ),
    ]
